### PR TITLE
PDF generator merge

### PR DESCRIPTION
**Pull request by chmunozpardo**
- Added PDF generator feature for testdata, health check and beam pattern.
- Merged conflicting files between the last two commits of the parent repository and the added PDF feature.
- Formatted many php files.
- Fixed a bug where exprted CSV files had too many trailing commas, making the CSV file not properly usable.

### CODE REVIEW

**Comment by morganmcleod** [comment]
Things I notice while reviewing this...

**First commit:**
Only formatting and indentation changes in lots of stuff.

Deleted dead code? plus formatting in:
FEConfig/AddNotesEtc.js

Added:
FEConfig/bp/bp_pdf.php
FEConfig/bp/pdf.css
FEConfig/testdata/health_check_pdf.php
FEConfig/testdata/pdf.css
FEConfig/testdata/pdf_tables.php
FEConfig/testdata/testdata_pdf.php

Do these duplicate existing classes or rename them?
classes/class.eff_html.php
classes/class.finelosweep_html.php
classes/class.noisetemp_html.php
classes/class.testdata_header_html.php
classes/class.wca_html.php

Do we need to keep this at all?   The code which previously used it to generate a Configured Item Data List (CIDL) was previously deleted and is certainly not needed anymore.
classes/tcpdf/*

I'll need to learn about these:
composer.json
composer.lock
fonts/*

This we have to merge carefully when we deploy:
config_main.php

When deploying to the production server I do this:

The deployed branch is osf_deployed
> git fetch origin master:master
> git merge master

Added:
nrao_logo.png

**Commit 2:**

This seems to reference a logo in your user directory so probably isn't right:
Also line 62 should work without using a hard-coded absolute path:
FEConfig/bp/bp_pdf.php

Same for these:
FEConfig/testdata/health_check_pdf.php
FEConfig/testdata/testdata_pdf.php

**Commit 3:**

Same for these:
FEConfig/bp/bp_pdf.php
FEConfig/testdata/health_check_pdf.php
FEConfig/testdata/testdata_pdf.php

**Commit 4:**

Deleted:
classes/PHPExcel/*
classes/tcpdf/*
libraries/pclzip/*
libraries/reader.php

good.

**Commit 5:**
.gitignore only

**Commit 6:**
Was this to fix the reported issue with a CCA PAI data package?
FEConfig/testdata/export_to_csv.php

I'm about to start on fixing the workmanship plots but I think we should merge all these changes first to avoid conflicts.
The only things I'm worried about are the logo references and absolute paths in commits 2 and 3.

**Comment by morganmcleod** [comment]
Also a few questions about first commit.   Above.

**Comment by chmunozpardo** [comment]
Replying to your notes:

**First commit:**
- Mainly formatting. Many files had inconsistent indenting.
- Duplicates classes with `_html` suffix are for the PDF generator, this classes return a string with the `html` information instead of delivering an `html` page.
- I deleted `tcpdf` in a later commit. It seems not being used at all.
- `composer.json` and `composer.lock` are files to use with `php composer` dependency manager. Read [Composer Dependency Management](https://getcomposer.org/doc/00-intro.md#dependency-management).
In this case are used to deploy mPDF locally.
The `fonts` folder is for storing fonts used in the PDF. In this case there are fonts from Ubuntu.
- `config_main.php` was only formatted. Indentation inconsistency.
- `nrao_logo.png` is a placeholder logo for the PDF file. This is later used as an absolute path, I will need to fix this.

**Second and third commit:**
- The paths are absolute because I had to fix this directly in the server after deploying in personal folder. Will fix this.

**Fouth commit:**
- This libraries seemed to be unused.

**Fifth commit:**
- Self explanatory.

**Sixth commit:**
- Fixed `FEConfig/testdata/export_to_csv.php` because when I tried to export the data, the files generated from the FETMS GUI had several unindented commas per row, which I had to delete manually after.
Visit and click on `Export CSV` in the following links:
  - [Current](http://fetms.osf.alma.cl/fetms/FEConfig/testdata/testdata.php?keyheader=78921&fc=40)
  - [Fixed](http://fetms.osf.alma.cl/cmunoz/fetms/FEConfig/testdata/testdata.php?keyheader=78921&fc=40)

**Comment by chmunozpardo** [comment]
Updated absolutes path from **Second and third commit**.

**Comment by morganmcleod** [comment]
I'm going to work on getting this merged today so I can move on to the other requested changes which are blocked by this.

I am concerned about having duplicate code in classes that generate HTML strings vs. HTTP replies.   This would mean that every bug fix or change would have to be made identically in two places.   It would be better to have the HTTP replies version implemented in terms of the HTML strings version.   But it is ok for now to get it merged and move on.

**Comment by chmunozpardo** [comment]
If you find it's better to have this classes merged, I could do it today no problem. I would use the same idea, having similar functions but with suffix appended to distinguish between both cases.

**Comment by morganmcleod** [comment]
That sounds like a better idea.

**Comment by chmunozpardo** [comment]
Files with similar class name merged using new functions with `_html` suffix in their names.

**Comment by morganmcleod** [comment]
I'm testing this on our test server here.   It does not have the PHP extensions installed yet.   So it is not surprising that clicking the beam pattern PDF report button gives an error.

Warning: require_once(/export/home/cvweb-dev/webtest.cv.nrao.edu/active/php/ntc/ws-mtm/ALMA-FETMS-www/vendor/autoload.php): failed to open stream: No such file or directory in /export/home/cvweb-dev/webtest.cv.nrao.edu/active/php/ntc/ws-mtm/ALMA-FETMS-www/FEConfig/bp/bp_pdf.php on line 3

Will vendor/autoload.php get installed with one of the extensions, or does that need to be part of this merge?

**Comment by morganmcleod** [comment]
Merging now.

Reviewing diffs between HEAD of master: 1b8370e and HEAD of this merge: 67e3e5a

classes/class.cryostat.php has missing closing quotes on lines 282, 305, 328
This is effectively dead code so these can be fixed up after the merge (or possibly deleted altogether.)

classes/class.eff.php and many others have functions like Display_ApertureEff_html() which return an HTML string rather than echoing it to the client.
These duplicate the functionality of companion functions like Display_ApertureEff().
This is fine and we will merge as-is, but then should follow up re-implementing each one in terms of the other e.g.:
    function Display_ApertureEff() {
        echo Display_ApertureEff_html();
    }

**Comment by chmunozpardo** [comment]
I forgot to mention. To make `php composer` install the packages mentioned in the file `composer.json`, it is necessary to first install `composer` locally or globally using [this instructions](https://getcomposer.org/download/). Practically the important commands are:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

This will download a file called `composer.phar` in the current folder. To run `composer`, you just run `php composer.phar install` in the folder containing the `composer.json` file and this will create a folder called `vendor` with all the dependencies from `mPDF` inside it.

**Comment by morganmcleod** [comment]
Done and deployed to fetms.osf.alma.cl.   Seems to be working.

**Pull request merged**
